### ISSUE TITLE
Implementing where clause fails

### ISSUE THREAD

**Issue by chrishunter-agspace** [leangen/graphql-spqr#5]
I have been requested to add a where clause to the codebase so that queries like this can be executed `users( where: { name: "Bob" } ) { name }`, but there appears to be a name conflict when doing this with more than one entity.

If I add in my UserQuery:

    public class UsersQuery {
    private UserRepository userRepository;
    @GraphQLQuery(name = "users")
    public List<Users> userSearch(@GraphQLArgument(name = "where",
                                                        description = "User where clause")
                                                 Map<String, Object> where)
                                                        throws Exception {
        ExampleMatcher matcher = ExampleMatcher.matching();
        User user = new User();
        for (String key : where.keySet()) {
                matcher.withMatcher(key, ignoreCase());
                PropertyUtils.setSimpleProperty(user, key, where.get(key));
        }

        Example<User> example = Example.of(user, matcher);
        return userRepository.findAll(example);
    }
    }

It appears to start correctly, but if I add a second one in a different query such as:

    public class BuildingsQuery {
    private BuildingRepository buildingRepository;
    @GraphQLQuery(name = "buildings")
    public List<Building> buildingSearch(@GraphQLArgument(name = "where",
                                                        description = "Building where clause")
                                                 Map<String, Object> where)
                                                        throws Exception {
        ExampleMatcher matcher = ExampleMatcher.matching();
        Building building = new Building();
        for (String key : where.keySet()) {
                matcher.withMatcher(key, ignoreCase());
                PropertyUtils.setSimpleProperty(building, key, where.get(key));
        }

        Example<Building> example = Example.of(building, matcher);
        return buildingRepository.findAll(example);
    }
    }

I get conflicts in the SchemaUtils.assertTypeUniqueness claiming "All types within a GraphQL schema must have unique names. No two provided types may have the same name." where my type has the name "mapEntry_String_Object_input" even though I defined the name as buildings. Am I misunderstanding what the name is, and if so, why are my other queries not conflicting?

**Comment by kaqqao** [comment]
Just to make sure, are you on the latest version? Because I thought I fixed this :|

**Comment by chrishunter-agspace** [comment]
I'm including 0.9.0 from maven.

**Comment by chrishunter-agspace** [comment]
Awesome, I see that maven has been updated with SPQR 0.9.1. Although I still have the issue, and I'm assuming it is because I shouldn't be using a Map and it should be some sort of concrete class?

Are you aware of any way I could work around this and pass a query a map for dynamic queries so I don't have to write queries for every eventuality and every entity?

**Comment by chrishunter-agspace** [comment]
Closing this, as I have resolved my issue, but posting this as there seems to be little enough documentation for graphQL Java, hopefully it should help someone.

POSTing {"query": "{users(user: {name: Bob}) {id, name}}"}

    @GraphQLQuery(name = "users")
    public List<User> userSearch(@GraphQLArgument(name = "user") User user)
            throws Exception {
        ExampleMatcher matcher = ExampleMatcher.matching();
        Map<String, Object> description = PropertyUtils.describe(user);
        description.keySet().forEach(key -> {
            if (description.get(key) != null) {
                matcher.withMatcher(key, ignoreCase());
            }
        });
        Example<User> example = Example.of(user, matcher);
        return userRepository.findAll(example);
    }

**Comment by kaqqao** [comment]
I've fixed your issue (it was indeed a bug). I'll push the fix tomorrow.

But, there were multiple problems with your original approach.

1. Inputs in GraphQL (like anything else) are strongly typed, meaning you can't just add arbitrary fields, as in your example with ` where: { name: "Bob" }`. This would mean the input type actually has a field called `name`. Otherwise, the query validation will fail.

2. Java maps are _very_ tricky. There's no way to map them to a GraphQL type, as the keys are dynamic. So graphql-spqr turns them into a list of `entry` object that have `key` and `value` properties. So that means the input would have to look something like:
`where: {key: "name", value:"Bob"}`

The type of the entry is different for each Java type, and are named `"mapEntry_" + keyType.getName() + "_" + valueType.getName();` and that's where the `mapEntry_String_Object_input ` was coming from.

3. `Object` class must be mapped as a scalar, as it is impossible to it to GraphQL in any meaningful way otherwise. What fields would it have? The new 0.9.2 version will by default map `Object` as a scalar.

The only reasonable way to achieve what you're after (a `Map` with an `Object` value), and keep the API clean (no `key`/`value` fields), is to treat the input map as a complex scalar. You'd achieve that like this:
```java
public List<Users> userSearch(@GraphQLArgument(name = "where", description = "User where clause")
    @GraphQLScalar Map<String, Object> where) throws Exception { //notice @GraphQLScalar
...
}
```
This will have the exactly the effect you're after.

But due to a bug, this will only work as of 0.9.2. I'll release it no later than this weekend.

**Comment by chrishunter-agspace** [comment]
Hopefully my second approach is better, because it enforces the mapping to an entity, but by using the ExampleMatcher to read from the newly created object being passed in, it allows me to have the generic search style. I believe I can still have it as a "where" clause, by just naming the graphQL argument as "where".

But I agree, the original thought process I was using was flawed through a misunderstanding I had on how this could be implemented.

**Comment by kaqqao** [comment]
Yup, the second approach is likely better as it gives you type safety. And yes, you can name the argument `where` anyway.

Join[ the Gitter room](https://gitter.im/leangen/graphql-spqr) if you need more help/advice.

Btw, just being curious, what kind of project are you using graphql-spqr for?

**Comment by 4shotespresso** [comment]
> Closing this, as I have resolved my issue, but posting this as there seems to be little enough documentation for graphQL Java, hopefully it should help someone.
> 
> POSTing {"query": "{users(user: {name: Bob}) {id, name}}"}
> 
> ```
> @GraphQLQuery(name = "users")
> public List<User> userSearch(@GraphQLArgument(name = "user") User user)
>         throws Exception {
>     ExampleMatcher matcher = ExampleMatcher.matching();
>     Map<String, Object> description = PropertyUtils.describe(user);
>     description.keySet().forEach(key -> {
>         if (description.get(key) != null) {
>             matcher.withMatcher(key, ignoreCase());
>         }
>     });
>     Example<User> example = Example.of(user, matcher);
>     return userRepository.findAll(example);
> }
> ```

Did this ExampleMatcher perform as expected for you?  I am trying something similar and always getting 0 results.  Trying to dynamically build my matcher based on key/value pairs in a map.  My matcher's property specifiers size always ends up 0. 
`
      Example example = null;

      if (null!=matcherMap) {
        ExampleMatcher matcher = ExampleMatcher.matchingAny();

        matcherMap.keySet().forEach(key -> {
          String value = (String) matcherMap.get(key);
          if (value != null) {
            if ("ignoreCase".equalsIgnoreCase(key)) {
              matcher.withIgnoreCase(Boolean.valueOf(value));
            }
            if ("startsWith".equalsIgnoreCase(value)) {
              matcher.withMatcher(key, startsWith());
            }
            if ("endsWith".equalsIgnoreCase(value)) {
              matcher.withMatcher(key, endsWith());
            }
            if ("contains".equalsIgnoreCase(value)) {
              matcher.withMatcher(key, contains());
            }
          }
        });
        logger.info("matcher: "+(matcher.toString()));
        example = Example.of(entity, matcher);
      } else {
        example = Example.of(entity);
      }
      logger.info("example: "+(example.toString()));
      return repo.findAll(example, PageRequest.of(page, size));
`
