### ISSUE TITLE
Subquery/Edges/...

### ISSUE THREAD

**Issue by depauwjimmy** [leangen/graphql-spqr#8]
Hello,

I have been trying for the past 2 days to use this and i am completely lost and confused.
The only thing i was able to achieve is a simple query that simply returns some users for instance.
But when there is subquery or edges involved i could not find any example/documentation on how to do it.
I tried everything i could trying to decipher the tests code but either nothing in my code for the subquery is called or i have a GraphQL exception which i have no idea how to resolve using spqr.

I see there is a Edge class but i don't know what to do with it, is it mandatory?
Why do my GraphQLQuery annotated method for a subquery is never called?
How do i pass parent information like a field to the subquery?
What relayId on GraphQLId do?

Is there an example somewhere that could help me? I have so many questions and no answer that i could find.
Something simple like post/comments and you want to have all the comments of a specific post in a single query would be a good example i think.

I feel this product could help me a lot but since there is no documentation/example whatsoever, i have no idea what to do.

Right now i want to use GraphQLContext User user in a subquery method to retrieve the parent.

`public List<Vote> getUserVotes(@GraphQLContext User user) {...}`

My user object has a Gender enum class and when the method is declared i receive the following exception : 

`graphql.AssertException: All types within a GraphQL schema must have unique names. No two provided types may have the same name.
No provided type may have a name which conflicts with any built in types (including Scalar and Introspection types).
You have redefined the type 'GenderInput' from being a 'GraphQLEnumType' to a 'GraphQLEnumType'`

Thanks a lot.

**Comment by kaqqao** [comment]
You're absolutely right, the documentation is the sore point of this project. I've been promising to do something abut for a while now, but it's a gigantic task...

In the meantime, can you post an example (or a link to a sample project if you have one) of what you're trying to achieve and I'll see to help you out.

**Comment by kaqqao** [comment]
Argh, the enum type is a genuine bug. I'll fix it immediately.
graphql-java changed the way it deals with duplicated types between versions 2 and 3, and graphql-spqr still has some leftover incompatibilities that pop up.

**Comment by depauwjimmy** [comment]
Ok if this is a bug i'll stop trying going around it :)
In the meantime i will remove the field to avoid it.

I'll explain what i want to achieve, since i am kinda stuck i don't have much of a project to provide.
My schema is : 
- One table User
- One table Entity
- One table Qualifier

A user can vote for an Entity using a qualifier.
So i have an edge/many-to-many relationship with 3 ids called "Vote"

I have a class User, Entity and Qualifier.
For instance my User class look like this : 

`package com.dcode.andhrimnir.engine.domain;

import io.leangen.graphql.annotations.GraphQLId;
import io.leangen.graphql.annotations.GraphQLNonNull;
import io.leangen.graphql.annotations.GraphQLQuery;

import java.net.URL;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.Locale;

public class User {
    @GraphQLId()
    @GraphQLQuery(name = "id", description = "A users's id")
    @GraphQLNonNull
    private String id;
    private String email;
    private String firstName;
    private String lastName;
    private String displayName;
    private URL avatar;
    @GraphQLNonNull
    private Gender gender;
    @GraphQLNonNull
    private Locale language;
    private LocalDate dateOfBirth;
    private int level;
    private LocalDateTime creationDate;
    private LocalDateTime updateDate;

   // Getters and setters
   // ...
}`

Other classes look the same, they have the same annotated id and query.
My questions there would be : 
- Do i have to add GraphQLId(relayId = true) for subquery to work? I'm not sure.
- Do i have to annotate the class with GraphQLType ?

I also have a UserQueries class that i registered on my GraphQLSchema using withOperationsFromSingleton.
I can do a simple query by id with : 
`@GraphQLQuery(name = "user")
    public User getUserById(@GraphQLId @GraphQLArgument(name = "id") @GraphQLNonNull String id) {
        ...
    }`

But where i am stuck completely is if i want to do a GraphQL query like : 
`{
	user(id:1565890985580299324) {
		firstName
		lastName
		email
		votes {
			entity {
				id
			}
			qualifier {
				id
			}
		}
	}
}`

I want all the votes the user did including the detail about the entity and qualifier.
I would want to reuse existing query by id for entity and qualifier if possible.
At this point i don't really know what to do.
What should i add to User, Entity, Qualifier, UserQueries classes?
Do i need to create a VoteEdge class that would implement Edge<Vote> ? Coming for a graph database i suppose you would only need it if i want to have metadata on the edge (like a vote date)

Thanks a lot for your help

**Comment by kaqqao** [comment]
I've just fixed the enum issue and released version 0.9.2 that also contains out-of-the-box support for some of the types you're using (`Locale`, `LocalDateTime`). 

You can get it immediately from [Bintray](https://bintray.com/leangen/maven) (should also sync with JCenter). Maven Central will sync in a couple of hours.

This will solve some of the issues you're having.

I'll also try answering some of the questions you're having:

* `relayId`, `Edge` etc are used for [Relay Connection spec](https://facebook.github.io/relay/graphql/connections.htm) compatibility, they're only of interest if you're using Relay as the client on the front-end.
* `@GraphQlType` is only used for meta-data: to override the type name and attach the description. Not mandatory.
* `@GraphQLContext ` is indeed the correct mechanism for injecting the enclosing object

You can find a working example at https://github.com/leangen/graphql-spqr-samples

I'll look into your specific example and give you more precise guidance a bit later, when I get a chance.

**Comment by string01** [comment]
Great thread. It's helpful in understanding how this works.
I'm still getting my head around the spec and how it maps to this API;
which is pretty intuitive and we'll implemented.
Thanks,
D

**Comment by kaqqao** [comment]
@depauwjimmy In my rush to fix the enum mapping, I missed a case when the same enum is used for both input and output 😨
I've now fixed it and added proper tests assuring uniqueness of all types, but it's not in 0.9.2... which means I'll have to release 0.9.3 _really_ soon.

**Comment by depauwjimmy** [comment]
@kaqqao Thanks a lot for your fix and your insight.
Oh so i won't bother with Edge, relayId and GraphQLType since it does not fit my need.
I guess what was misleading to me was the exception i had with my enum Gender and the bug i encountered when using GraphQLContext.
I'll try it out without the enum type as to be sure i can understand how injection works.
I can wait to put back the enum once the 0.9.3 comes out.

**Comment by depauwjimmy** [comment]
I think i figured it out. I was on the right track when using GraphQLContext but i wanted to use it on an object that triggered the enum type exception bug which led me to think i was not using it properly.
Oh well :)
In the end it is really simple and now that i get it to work, your product is really nice to quickly get a graphql product started.

I have a simple question about optimizing my queries.
If the graphql query contains only the fields "id" and "name" for example, i would rather not do a "SELECT * FROM...."
Is there a way to map field asked in the query and fields for my select statement?

I have put aside my enum for now since i am using it for both input and ouput.

Thanks again

**Comment by kaqqao** [comment]
Good to hear you're back on track! 0.9.3 is out now, so you might want to give it a go.

**Comment by kaqqao** [comment]
As for the `SELECT ... FROM ...` optimization, it is possible, but at this moment not very convenient.

If the current field is an object type, you can get the sub-field names injected simply via `@GraphQLEnvironment Set<String> subFields` parameter, e.g.

```java
@GraphQLQuery(name = "userVotes")
public List<Vote> getUserVotes(@GraphQLContext User user, @GraphQLEnvironment Set<String> subFields) {
    //do a SELECT here using the field names from subFields
   ...
} 
```

But, if the current field is not an object, there's no such easy way to inject the sub-fields. But what you can still do in inject `@GraphQLEnvironment ResolutionEnvironment env`, from here you can get a hold of `DataFetchingEnvironment` via `env.dataFetchingEnvironment` and from there you can get the current field and it's sub-selections, but it gets tricky with aliases, conditional selects etc. I'll rework the sub-selection injection soon to be able to deal with all these cases.

**Comment by kaqqao** [comment]
I'll close this one as the enum bug has been fixed and I've opened #9 to track the progress of the sub-field injection feature.
